---
- name: Configure pESX
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Add ESXi Host to VCSA
      vmware_host:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        validate_certs: false
        cluster_name: "Management"
        esxi_hostname: "{{ physicalESX.host }}"
        esxi_username: "root"
        esxi_password: "{{ physicalESX.password }}"
        state: present
