---
- name: Configure pESX
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Add ESXi Host to VCSA
      vmware_host:
        hostname: "{{ vc_mng.ip }}"
        username: "{{ vc_mng.user }}"
        password: "{{ vc_mng.password }}"
        datacenter_name: "{{ vc_mng.datacenter }}"
        validate_certs: false
        cluster_name: "Management"
        esxi_hostname: "{{ physicalESX.host }}"
        esxi_username: "root"
        esxi_password: "{{ physicalESX.password }}"
        state: present
      when: vcenter.ip  ==  vc_mng.ip
