---
# - import_playbook: playbooks/connectPESXtoVC.yml

- name: Wait 5 more minutes the vESXi hosts to become fully responsive
  hosts: localhost
  gather_facts: False
  vars_files:
    - ./answerfile.yml
- import_playbook: playbooks/deployVC.yml

