---
- name: Prepare Physical ESXi
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Add a vSwitch
      vmware_vswitch:
        hostname: "{{ physicalESX.host }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        switch: vSwitch1
        nics:
        - vmnic1
        - vmnic2
        mtu: 1500
        validate_certs: False

    - name: Add a portgroup
      vmware_portgroup:
        hostname: "{{ physicalESX.host }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        esxi_hostname: "{{ physicalESX.host }}"
        switch_name: vSwitch1
        portgroup_name: allVlan
        vlan_id: 4095
        network_policy:
          promiscuous_mode: True
        validate_certs: False

    - name: Create a vmkernel
      vmware_vmkernel:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password}}"
        esxi_hostname: "{{ physicalESX.host }}"
        portgroup_name: allVlan
        vswitch_name: vSwitch1
        state: present
        validate_certs: False
        network:
          type: 'static'
          ip_address: 192.168.6.109
          subnet_mask: 255.255.255.0
